version: '3.8'

services:
  frontend:
    build: './frontend'
    ports:
      - '3000:3000'
    restart: 'on-failure'
    env_file:
      - ./frontend/.env
    networks:
      - 'frontend'

  backend:
    build: './backend'
    ports:
      - '8080:8080'
    restart: 'on-failure'
    env_file:
      - ./backend/.env
    networks:
      - 'frontend'
      - 'backend'
    links:
      - frontend

networks:
  frontend:
  backend: