version: '3.8'

services:
  nginx:
    depends_on:
      - frontend
    build: './frontend/nginx'
    networks:
      - 'frontend'
      - 'backend'
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx:/app

  frontend:
    depends_on:
      - backend
    build: './frontend'
    ports:
      - '3000:3000'
    restart: 'on-failure'
    env_file:
      - ./frontend/.env
    networks:
      - 'frontend'
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend:
    build: './backend'
    ports:
      - '8080:1337'
    restart: 'on-failure'
    env_file:
      - ./backend/.env
    networks:
      - 'frontend'
      - 'backend'
    volumes:
      - /app/node_modules
      - ./backend:/app

networks:
  frontend:
  backend: