version: '3.8'

services:
  backend:
    container_name: 'personalwebsite_backend'
    build: './backend'
    ports:
      - '8080:8080'
    links:
      - redis
    restart: 'on-failure'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_SESSION_SECRET=${REDIS_SESSION_SECRET}

  postgres:
    container_name: 'personalwebsite_postgres'
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
volumes:
  postgres: